redisHost = 'localhost'
redisPort = 6379
NEWS_TABLE_NAME = "newCollection"
CLICK_LOGS_TABLE_NAME = 'click_logs'
NEWS_LIMIT = 100
NEWS_LIST_BATCH_SIZE = 10
USER_NEWS_TIME_OUT_IN_SECONDS = 600
NEWS_TIME_OUT_IN_SECONDS = 3600 * 24
SLEEP_TIME_IN_SECONDS = 10

## Kafka Topic
DEDUPE_NEWS_TASK_QUEUE = 'DEDUPE_NEWS_TASK_QUEUE'
SCRAPE_NEWS_TASK_QUEUE = 'SCRAPE_NEWS_TASK_QUEUE'
LOG_CLICKS_TASK_QUEUE = 'LOG_CLICKS_TASK_QUEUE'

Service_SERVER_PORT = 4040
KAFKA_SERVER = ['ec2-54-175-141-176.compute-1.amazonaws.com:9092', 'ec2-34-207-91-169.compute-1.amazonaws.com:9092']
MONGO_DB_PORT = '27017'

PREFERENCE_MODEL_TABLE_NAME = "user_preference_model"
Recommendation_SERVER_PORT = 5050

SAME_NEWS_SIMILARITY_THRESHOLD = 0.9

SERVER_HOST = 'ec2-107-23-249-234.compute-1.amazonaws.com'
MONGO_DB_HOST = 'localhost'
DB_NAME = 'RecommendationNews'
