redisPort = 6379
NEWS_TABLE_NAME = "newCollection"
CLICK_LOGS_TABLE_NAME = 'click_logs'
NEWS_LIMIT = 100
NEWS_LIST_BATCH_SIZE = 10
USER_NEWS_TIME_OUT_IN_SECONDS = 600

## Kafka Topic
DEDUPE_NEWS_TASK_QUEUE = 'DEDUPE_NEWS_TASK_QUEUE'
SCRAPE_NEWS_TASK_QUEUE = 'SCRAPE_NEWS_TASK_QUEUE'
LOG_CLICKS_TASK_QUEUE = 'LOG_CLICKS_TASK_QUEUE'

Service_SERVER_PORT = 4040
KAFKA_SERVER = 'localhost:9092'
MONGO_DB_PORT = '27017'

PREFERENCE_MODEL_TABLE_NAME = "user_preference_model"
Recommendation_SERVER_PORT = 5050
